### ISSUE TITLE
Defining custom type conversion for schema migrations

### ISSUE THREAD

**Issue by CptWesley** [JasperFx/weasel#127]
We're currently running into a situation where we (using Marten 6.4.1) are trying to add a duplicated index to an existing table that contains data. We are using `ApplyAllConfiguredChangesToDatabaseAsync` to apply the schema changes to the database. This appears to be using functionality for schema upgrades that have been implemented in Weasel, hence why I am asking this question here. This seems to work well for any integer and string types, but it seems to fail for `DateTime`, `Guid` and custom type properties (which are converted to varchars in the JSON and when querying) when trying to fill the columns.

For the `DateTime` upgrade it fails with the following message:
```
      ----> Npgsql.PostgresException : 42804: column "document_time" is of type timestamp without time zone but expression is of type character varying

POSITION: 78
Data:
  Severity: ERROR
  InvariantSeverity: ERROR
  SqlState: 42804
  MessageText: column "document_time" is of type timestamp without time zone but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 78
  File: parse_target.c
  Line: 594
  Routine: transformAssignedExpr
```

For the `Guid` upgrade it fails with the following message:
```
      ----> Npgsql.PostgresException : 42804: column "document_value" is of type uuid but expression is of type character varying

POSITION: 79
Data:
  Severity: ERROR
  InvariantSeverity: ERROR
  SqlState: 42804
  MessageText: column "document_value" is of type uuid but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
  Position: 79
  File: parse_target.c
  Line: 594
  Routine: transformAssignedExpr
```

It appears that the migration is not aware that it should cast/transform the string json field when trying to fill the column. Is there any way to configure weasel (or marten) in order to support these casts/transformations?
